kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "sleepy"
spec:
  template:
    metadata:
      labels:
        name: "sleepy"
    spec:
      containers:
        - name: "sleepy"
          image: "registry.access.redhat.com/ubi8-micro:latest"
          command:
          - "sleep"
          - "604800"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
  replicas: 50
