apiVersion: v1
kind: Pod
metadata:
  name: sleepy
  labels:
    app: sleepy
spec:
  containers:
  - image: registry.access.redhat.com/ubi8-micro:latest
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: sleepy
  restartPolicy: Always